// Cooking, step by step. Each recipe is a short sequence of things to do at the real places in the kitchen: the kudam for water, the hearth, the shelf,
// the ammikkallu, the ural, the chirava, the puttukutti, the leaf to serve on. A step is a tap, a few strokes, a stirred circle, or a few drops.
// kinds: tap · strokes (back and forth, n) · circle (round and round, n sectors) · taps (n taps) · pull (up and down, n)
const S = (at, kind, text, ml, n = 1) => ({ at, kind, text, ml, n });
const fire = S('viraku', 'tap', 'Feed the aduppu first; the fire has gone low.', 'അടുപ്പിൽ വിറക്');
export const STEPS = {
  kaapi: [S('kudam', 'tap', 'Water from the kudam into the chembu.', 'വെള്ളം'), S('chembu', 'tap', 'The chembu on the fire. Wait for the first rattle.', 'അടുപ്പിൽ'), S('shelf', 'tap', 'Two spoons of kaappippodi from the jar, jaggery in the glass.', 'കാപ്പിപ്പൊടി'), S('chembu', 'pull', 'Pour it between the glass and the tumbler, high, three times.', 'അടിച്ചു പതപ്പിക്കുക', 3)],
  chaya: [S('kudam', 'tap', 'Water into the chembu.', 'വെള്ളം'), S('chembu', 'tap', 'On the fire, a pinch of tea dust when it boils.', 'ചായപ്പൊടി'), S('shelf', 'tap', 'Milk from the pot, sugar from the tin.', 'പാൽ'), S('chembu', 'pull', 'Pull it long between two glasses, a metre of it.', 'അടിച്ചു പതപ്പിക്കുക', 3)],
  kanji: [S('kudam', 'tap', 'Wash the rice three times in the chatti.', 'അരി കഴുകുക'), S('chatti', 'tap', 'On the fire, more water than you think; let it boil over once.', 'വേവിക്കുക'), S('ammikkallu', 'strokes', 'Coconut, green chilli, shallot, tamarind: grind the chammanthi.', 'ചമ്മന്തി അരയ്ക്കുക', 6), S('serve', 'tap', 'Into the wide bowl, a plavila folded for a spoon.', 'വിളമ്പുക')],
  puttu: [S('chirava', 'strokes', 'Grate the coconut on the chirava.', 'തേങ്ങ ചിരകുക', 5), S('kudam', 'tap', 'Sprinkle water into the flour and work it with your fingers.', 'പൊടി നനയ്ക്കുക'), S('puttukutti', 'tap', 'Flour, coconut, flour, coconut, in the bamboo kutti.', 'പുട്ടുകുറ്റിയിൽ'), S('chembu', 'tap', 'On the chembu; when the steam comes through the top, it is done.', 'ആവി കയറ്റുക')],
  dosa: [S('ural', 'taps', 'Pound the soaked rice to a batter.', 'അരി ഇടിക്കുക', 4), S('chatti', 'tap', 'The iron kallu on the fire, rubbed with an onion dipped in oil.', 'ദോശക്കല്ല്'), S('chatti', 'circle', 'A ladle of batter, spread outward in one circle.', 'ദോശ പരത്തുക', 12), S('serve', 'tap', 'Off the kallu with the flat spoon. The first is for the crows.', 'വിളമ്പുക')],
  kappa: [S('kudam', 'tap', 'Peel the kappa and boil it till it breaks.', 'കപ്പ വേവിക്കുക'), S('chirava', 'strokes', 'Grate the coconut.', 'തേങ്ങ ചിരകുക', 4), S('ammikkallu', 'strokes', 'Grind red chilli, coconut and turmeric for the curry.', 'അരയ്ക്കുക', 6), S('chatti', 'tap', 'Mathi and kudampuli in the manchatti; let it sour.', 'മീൻകറി'), S('serve', 'tap', 'Kappa on the leaf, the curry over it.', 'വിളമ്പുക')],
  meencurry: [S('chirava', 'strokes', 'Grate half a coconut.', 'തേങ്ങ ചിരകുക', 4), S('ammikkallu', 'strokes', 'Grind it red with chilli and a little turmeric.', 'അരയ്ക്കുക', 6), S('chatti', 'tap', 'Mathi in the manchatti, kudampuli, the paste, water to cover. Do not stir; shake the pot.', 'മീൻകറി'), S('serve', 'tap', 'Better tomorrow. Serve some today anyway.', 'വിളമ്പുക')],
  avial: [S('chatti', 'tap', 'Every vegetable in the thodi cut long, into the chatti with turmeric.', 'പച്ചക്കറി'), S('chirava', 'strokes', 'Grate the coconut.', 'തേങ്ങ ചിരകുക', 4), S('ammikkallu', 'strokes', 'Coconut, cumin, green chilli: coarse, not smooth.', 'അരയ്ക്കുക', 5), S('chatti', 'tap', 'Mix it in with the curd, a spoon of raw velichenna on top.', 'അവിയൽ'), S('serve', 'tap', 'On the leaf.', 'വിളമ്പുക')],
  pazhampori: [S('ural', 'taps', 'Flour, a pinch of turmeric, water, to a batter that falls slowly.', 'മാവ്', 3), S('chatti', 'tap', 'Oil in the chatti till a drop of batter rises at once.', 'എണ്ണ'), S('chatti', 'taps', 'Dip each slice of plantain and slide it in, away from you.', 'പഴംപൊരി', 3), S('serve', 'tap', 'On yesterday’s newspaper to drain, then on the plate.', 'വിളമ്പുക')],
  chakka: [S('chatti', 'tap', 'Raw jackfruit cut small, in the chatti with turmeric and salt.', 'ചക്ക'), S('chirava', 'strokes', 'Grate the coconut.', 'തേങ്ങ ചിരകുക', 4), S('ammikkallu', 'strokes', 'Coconut, cumin, garlic, coarse.', 'അരയ്ക്കുക', 4), S('chatti', 'tap', 'Mash it all together with the back of the ladle.', 'പുഴുക്ക്'), S('serve', 'tap', 'With a spoon of velichenna.', 'വിളമ്പുക')],
  payasam: [S('kudam', 'tap', 'Milk and water in the uruli, on a low fire.', 'പാൽ'), S('chatti', 'circle', 'Stir. Keep stirring. The bottom must never catch.', 'ഇളക്കുക', 14), S('shelf', 'tap', 'The ada, then the sugar, then more stirring.', 'അട'), S('serve', 'tap', 'When the spoon stands up, it is done. Cardamom. Serve.', 'വിളമ്പുക')],
  unniyappam: [S('ural', 'taps', 'Rice, jaggery, banana, pounded to a dark batter.', 'മാവ്', 4), S('chatti', 'tap', 'The iron appakkara on the fire, oil in each cup.', 'അപ്പക്കാര'), S('chatti', 'taps', 'A spoon into each cup; turn them with the stick when the edges brown.', 'ഉണ്ണിയപ്പം', 3), S('serve', 'tap', 'Into the tin. Burn a finger. Tradition.', 'വിളമ്പുക')],
  eggroast: [S('kudam', 'tap', 'Eggs in water, boiled hard.', 'മുട്ട പുഴുങ്ങുക'), S('chatti', 'tap', 'Onion in oil, slow, till it is brown and sweet. This takes as long as it takes.', 'ഉള്ളി വഴറ്റുക'), S('chatti', 'taps', 'The eggs in, halved, tossed in the masala.', 'റോസ്റ്റ്', 2), S('serve', 'tap', 'On the leaf, with curry leaves.', 'വിളമ്പുക')],
  thiruvathira: [S('kudam', 'tap', 'Wash the eight tubers: kappa, chena, chembu, kachil, koorka…', 'എട്ടങ്ങാടി'), S('chatti', 'tap', 'Roast them in the fire, then into the chatti with beans.', 'ചുട്ടെടുക്കുക'), S('chirava', 'strokes', 'Grate the coconut.', 'തേങ്ങ ചിരകുക', 4), S('chatti', 'tap', 'Coconut, jaggery, a little banana; mix with the hand.', 'പുഴുക്ക്'), S('serve', 'tap', 'For the women dancing tonight.', 'വിളമ്പുക')],
  karkidakakanji: [S('shelf', 'tap', 'The vaidyan’s herbs: fenugreek, cumin, dashapushpam, ashtachoornam.', 'മരുന്ന്'), S('kudam', 'tap', 'Navara rice washed, in the chatti with the herbs.', 'ഞവര അരി'), S('chatti', 'circle', 'Simmer long and slow; stir so the bottom does not catch.', 'ഇളക്കുക', 10), S('serve', 'tap', 'Milk and jaggery at the end. Bitter, warm, and good for you.', 'വിളമ്പുക')],
  sadya: [S('chirava', 'strokes', 'Four coconuts to grate. Start now.', 'തേങ്ങ ചിരകുക', 8), S('ammikkallu', 'strokes', 'Grind for the avial, the thoran, the erissery.', 'അരയ്ക്കുക', 8), S('chatti', 'tap', 'Sambar, avial, thoran, olan, kalan, pachadi: the chatti does not stop till noon.', 'കറികൾ'), S('chatti', 'circle', 'The payasam in the uruli; stir till the spoon stands.', 'പായസം', 12), S('serve', 'tap', 'Lay the leaf, tip to the left. Twenty-six things in their right places.', 'ഇല ഇടുക')]
};
export function stepsFor(r, fireLow) { const base = STEPS[r.id] || [S(r.where === 'chembu' ? 'chembu' : 'chatti', 'tap', 'Cook it on the fire.', 'വെക്കുക'), S('serve', 'tap', 'Serve.', 'വിളമ്പുക')]; return fireLow ? [fire, ...base] : base; }
// where each step is done, in kitchen coordinates (the hotspots), and which hotspot label it answers to
export const STEP_SPOT = { viraku: 'viraku', kudam: 'kudam', chembu: 'chembu', chatti: 'chatti', shelf: 'Amma’s notebook', ammikkallu: 'ammikkallu', ural: 'ural', chirava: 'chirava', puttukutti: 'puttukutti', serve: 'serve' };
