// Letters from Ravi, the younger brother who left for Madras and then the Gulf. Delivered by the postman every few days.
// What Ravi writes back about, depending on what you told him. One paragraph before his letter, in Madras or in the Gulf.
export const REPLIES = {
  rain: { madras: 'You wrote about the rain and I read it on the mill roof where it has not rained in a month. I could hear the tiles. Do not stop writing about the rain.', gulf: 'Your rain letter is in my shirt pocket. I read it to a man from Kottayam at lunch and he had to go and stand outside. Keep writing the rain. There is none here, only sand that behaves like it.' },
  cow: { madras: 'Lakshmi gave well? Tell Kuttan to whistle the other song, she prefers it. I think about her more than is normal for a man in a city. Do not tell her.', gulf: 'You wrote about the milk and I could taste the first kaapi of the morning in a canteen that serves tea in paper. Pat her once from me. On the neck, not the head, she hates the head.' },
  village: { madras: 'Velayudhan’s knee, Kunjappan’s book, who married whom: I read your page three times and laughed in the wrong places so the room-mate thinks I am mad. Write the whole kavala again next time.', gulf: 'Your kavala letter went round the camp. Two Palakkad men and a Kottayam man now know Velayudhan’s knee by name. Kunjappan should charge us. Write everyone again.' },
  quiet: { madras: 'You wrote the thing. I read it once and put it under the pillow and did not sleep. I am writing it back to you now and then the rain, as you did, to balance. We are both home when we write.', gulf: 'You wrote the thing we do not say. I have it here. I will not write it back, Chettaa; I will come and say it on the charupadi where it belongs. Keep the lamp.' }
};
export const LETTERS = [
  { from: 'Ravi, Madras', text: 'Chettaa, I have reached. The room is small and the city is loud and nobody here knows how to make kaapi. The mill gives us tea in tumblers the size of a thimble. Tell Amma’s thulasi I said hello. Write to me about the rain. — Ravi' },
  { from: 'Ravi, Madras', text: 'The typing class is going well. Forty words a minute now. The teacher is a Tamil lady who calls me “Malayalam boy” and gives me extra practice. I dreamt of the nadumuttam last night, with the rain falling only in the square. Is the swing still there? — Ravi' },
  { from: 'Ammini chechi (left at the step)', text: 'Mone, your Amma’s payasam recipe. Half the jaggery melted first, then the rest at the end. Do not let it boil over. I will know. — Ammini' },
  { from: 'Ravi, Madras', text: 'There is talk here of the Gulf. A man from Chavakkad went on a launch and came back in two years with a radio, a watch and a Yezdi. Everyone is applying. I am applying. Do not tell the neighbours yet. — Ravi' },
  { from: 'Ravi, Dubai', text: 'Chettaa, the sand here is not like our sand. It is in everything, even the bread. But the money is real. I am sending a draft to the post office; buy a new chembu, the old one leaks, I know it does. And light the lamp for Amma on Thiruvonam. — Ravi' },
  { from: 'Ravi, Dubai', text: 'I bought a cassette player. Yesudas all night. The Arab foreman asked what the song was about and I said it was about a river. It is about everything, but a river was easier. How is the cow? Has she forgiven me for the time with the firecrackers? — Ravi' },
  { from: 'The Vayanasala committee', text: 'Dear member, the Grandhasala Sangham reminds you that the Thakazhi novel borrowed in Chingam is overdue. There is a reading on Sunday evening. Tea will be served. Vayichu valaruka. — Secretary' },
  { from: 'Ravi, Dubai', text: 'Leave approved. Two months. I will come by the Jayanthi Janata to Shoranur and then the bus. Do not come to the stop, I know the way home; it is the one past the chayakkada where Velayudhan will stop me for an hour. Keep the kadala curry. — Ravi' },
  { from: 'Ravi (a telegram)', text: 'REACHING THURSDAY MORNING BUS STOP LIGHT THE LAMP STOP RAVI' },
  { from: 'Ravi, back in Dubai', text: 'Two months went like one afternoon. I keep the plavila spoon you gave me in my shirt pocket at work; the foreman thinks it is a charm. It is. Every evening at six-thirty I stop and think of the bell. Keep the house. — Ravi' }
];
