// People who remember you. Five villagers, each with a year of small beats that unlock by the calendar and by what you have done.
// A beat is one conversation and one visible change afterwards. Beats are independent: a calendar beat that is missed waits for next year,
// the others come in order with a few days between them. Nothing is lost by being away.
import { state, remember, save } from './state.js';
import { clock } from './clock.js';
import { fest } from './festivals.js';
import { talk } from './dialogue.js';
import { add } from './pantry.js';
import { audio } from '../engine/audio.js';
import { haptics } from '../engine/haptics.js';

const A = 'അമ്മിണി ചേച്ചി', V = 'വേലായുധൻ', K = 'കുഞ്ഞപ്പൻ', P = 'പാപ്പൻ', C = 'കുട്ടികൾ';
export const ARCS = {
  ammini: { name: 'Ammini chechi', beats: [
    { id: 'thin', lines: [['Ammini chechi, at the gate with a covered plate: “You are thin. Madras did that, or a woman did, and either way the cure is the same.”', A], ['Under the plavila: two idiyappam and a boiled egg. “Return the plate. Not the egg.”']], diary: 'Ammini chechi has decided I am thin and that it is her problem. Idiyappam at the gate, with instructions about the plate.', after: () => add('eggs', 1) },
    { id: 'letter', lines: [['Ammini chechi, a letter held like a snake: “Mone, read this. It is from my Suresh in Bombay. It is in English, because he is a big man now.”', A], ['You read it. Rent, a room-mate from Kottayam, a line about missing her sambar. You read that line twice, slowly, and she looks at the paddy while you do.'], ['“He writes well,” she says. “Too well. A boy who writes that well is not eating.”']], diary: 'Read Ammini chechi her son’s letter from Bombay. She cannot read English and would not ask her own family. I read the sambar line twice. She pretended it was the sun in her eyes.' },
    { id: 'cutting', lines: [['Ammini chechi with a stick wrapped in wet cloth: “Chembarathi. The red one, from the bush your Amma took a cutting of from my mother. Plant it by the step. It knows this house.”', A]], diary: 'Ammini chechi brought a chembarathi cutting from a bush that came from our bush that came from her mother’s. It is in a pot by the step now. Gardening here is genealogy.', flag: 'cutting' },
    { id: 'thiruvathira', gate: f => f.dhanu, lines: [['Ammini chechi: “Thiruvathira. The women are dancing at the Variath house tonight. Carry my lamp as far as the gate; after that it is not for men. Your Amma danced until her knees said no, and then she sang.”', A]], diary: 'Carried Ammini chechi’s lamp to the Variath gate on Thiruvathira night and heard the women singing from the lane. Amma was in that circle for forty years.' },
    { id: 'kanji', gate: f => f.karkidakam, lines: [['Kuttan, with the milk: “Ammini chechi has fever. Three days. She says tell nobody, so I am telling everybody.”', 'പാൽക്കാരൻ'], ['You take kanji in the brass chembu through the rain, the way she took it to this house for a month once. She says it needs salt. It does not need salt.']], diary: 'Took kanji through the Karkidakam rain to Ammini chechi, who had fever and had told Kuttan to tell nobody. She said it needed salt. She ate all of it.' },
    { id: 'amma', lines: [['Ammini chechi, on the charupadi, not looking at you: “Your Amma’s last year. You should know. She was not sad. She was busy. She planted that konna knowing. She wrote to both of you every week and posted every other one.”', A], ['“The ones she did not post are in the petti. I was not supposed to tell you. I am old, I forget what I was not supposed to do.”']], diary: 'Ammini chechi told me about Amma’s last year, which nobody else would. She was busy, not sad. There are unposted letters in the petti. I have not opened it yet.' },
    { id: 'onam', gate: f => f.thiruvonam, lines: [['Ammini chechi, in a new mundu, sitting down exactly where she always says Amma sat: “Thiruvonam. Payasam first, then opinions. The pookalam is crooked on the left. It was crooked on the left in 1961 too.”', A], ['She stays until the lamp. She has stayed until the lamp every Thiruvonam of your life.']], diary: 'Thiruvonam. Ammini chechi on the charupadi until the lamp, as every year. The pookalam is crooked on the left and always has been. Some things a house keeps without being asked.' }
  ] },
  velayudhan: { name: 'Velayudhan', beats: [
    { id: 'knee', lines: [['Velayudhan, pouring from a height: “The knee is the Congress. Fine in the morning, gone by evening, and everybody has an opinion about it.”', V], ['“Your Achan sat on that bench and lost every argument to me for thirty years. Deliberately. That is friendship.”']], diary: 'Velayudhan on his knee and the Congress, which are the same subject. He says Achan lost arguments to him on purpose for thirty years. I believe it.' },
    { id: 'results', lines: [['Velayudhan, not looking up from the kettle: “Her results came. First class. The first in this family to see a first class that was not a bus.”', V], ['He pours you a chaya you did not order and does not take money for it, which has not happened in the history of the shop.']], diary: 'Velayudhan’s daughter got a first class. He gave me a free chaya, which is the loudest thing he has ever said.' },
    { id: 'petition', lines: [['Velayudhan: “The road. Every monsoon the bus stops at the banyan and the old people walk. Write to the panchayat. You have the English and the handwriting; I have the signatures.”', V], ['Forty-one signatures, three thumbprints, and a drawing of the pothole by one of the children. You write it on the bench while he dictates adjectives.']], diary: 'Wrote the petition about the kavala road with Velayudhan dictating adjectives. Forty-one signatures and a child’s drawing of the pothole. Posted it at the kavala.' },
    { id: 'radio', lines: [['Velayudhan, with a screwdriver and no plan: “The radio. The cricket is tomorrow and the valve has gone. Your Achan could fix anything with a bidi and bad language.”', V], ['A loose wire, a clean contact, a prayer. Akashvani comes back mid-sentence and the whole bench applauds as if you had scored.']], diary: 'Fixed the chayakkada radio in time for the cricket. A loose wire and Achan’s method. The bench applauded. Velayudhan said it was luck, twice, which is how he says thank you.', flag: 'radio' },
    { id: 'road', gate: () => !!(state.rel.velayudhan && state.rel.velayudhan.done.petition), lines: [['Velayudhan, pointing with the kettle: “Look. Tar. From the banyan to the post office. The panchayat member came himself to be seen standing on it.”', V], ['“Your letter did that. Also the election. Mostly the election. But your letter.”']], diary: 'The kavala road is tarred from the banyan to the post office. Velayudhan credits my letter and the election, in that order when he is talking to me.', flag: 'road' },
    { id: 'gulf', lines: [['Velayudhan, quietly for once: “She has a job. Dubai. A hospital. She leaves after Vishu.”', V], ['“Your Ravi went, your Amma kept the lamp. Now I keep the lamp. Tell me it is the right thing.” You tell him. He already knows; he wanted to hear it in your Achan’s voice.']], diary: 'Velayudhan’s daughter is going to Dubai after Vishu. He asked me to tell him it was right, in Achan’s voice. I did my best with it.' },
    { id: 'onam', gate: f => f.thiruvonam, lines: [['Velayudhan, at your gate, in a shirt: “Closed. First time in thirty-one years. The board says Thiruvonam. It is not a lie.”', V], ['He eats two leaves of sadya and criticises the avial with his mouth full, which is praise.']], diary: 'Velayudhan closed the chayakkada for Thiruvonam, the first time in thirty-one years, and came for sadya. He criticised the avial with his mouth full. We have never been closer.' }
  ] },
  kunjappan: { name: 'Kunjappan', beats: [
    { id: 'book', lines: [['Kunjappan, turning the pattu-pusthakam to a page gone soft: “Your Amma’s page. Her handwriting is better than my sums. I kept the page. I keep all the pages.”', K]], diary: 'Kunjappan showed me Amma’s page in the credit book. He keeps every page, settled or not. The shop is a library of who owed whom and who forgave it.' },
    { id: 'son', lines: [['Kunjappan: “My son wants to sell. A bakery, he says. With glass. People will come for cake, he says. People come for rice and to be known.”', K], ['“Tell him. He listens to people who have been to Madras.” You tell him nothing. You buy rice. Kunjappan writes it in the book, slowly, so his son can see the page.']], diary: 'Kunjappan’s son wants to turn the kada into a bakery with glass. Kunjappan wrote my rice in the book very slowly so the boy would watch. I did not take sides. I bought rice.' },
    { id: 'parle', lines: [['Kunjappan, arranging biscuit packets like a man at a funeral: “Parle-G. Glucose. The children will not eat kuzhalappam now. In my father’s time they ate what the field gave. In my time they ate what the kada had. Now they eat what the lorry brings.”', K], ['“I have put the kuzhalappam jar next to it. Let the children decide. They decide wrong, but let them.”']], diary: 'Kunjappan has put the kuzhalappam jar beside the Parle-G and is letting the children decide. He says they decide wrong. The jar is half empty, so not entirely.' },
    { id: 'rahukalam', lines: [['Kunjappan, with the Mathrubhumi calendar and his glasses on his forehead: “Read me the rahukalam for Kanni eighteen. My daughter’s wedding. The astrologer says one thing and the calendar another and I trust paper.”', K], ['You read it. He writes it on the back of a bill. “Good. The muhurtham before the bad hour. Come. Bring Ammini. She will come anyway.”']], diary: 'Read the rahukalam off the kitchen calendar for Kunjappan’s daughter’s wedding on Kanni 18. He trusts paper over astrologers. He wrote the muhurtham on the back of a bill.', flag: 'invited' },
    { id: 'wedding', gate: f => f.wedding, lines: [['The wedding at the ambalam: Kunjappan in a new mundu that still has the fold lines, giving his daughter away with the face of a man handing over the ledger.', K], ['He finds you in the sadya line. “Second helping. No book today.” It is the most generous sentence in the language.']], diary: 'Kunjappan’s daughter married at the ambalam. He gave her away with the face of a man closing an account he never wanted to close. Second helping, no book.' },
    { id: 'page', lines: [['Kunjappan, closing the book with both hands: “Your Amma’s page is settled. It was settled years ago. By her. In paddy, in jackfruit, in two months of my mother’s medicines when I had nothing. I kept the page open so the house would keep coming.”', K]], diary: 'Amma’s page in Kunjappan’s book was settled years ago, by her, in paddy and kindness. He kept it open so the house would keep coming to the shop. I bought jaggery I did not need.' },
    { id: 'onam', gate: f => f.thiruvonam, lines: [['Kunjappan, at the kada door with a packet: “Chandrika. For Onam. No book. Do not argue, I have argued with better.”', K]], diary: 'Kunjappan gave me Chandrika soap for Onam and refused to write it down. From him this is a hug.', after: () => { state.items.chandrika = true; } }
  ] },
  pappan: { name: 'Pappan', beats: [
    { id: 'annas', lines: [['Pappan, standing as always: “Your Achan paid four annas and argued about it. Your Amma paid nothing and I argued about that. You will pay what you pay.”', P]], diary: 'Pappan’s fares: Achan paid and argued, Amma paid nothing and Pappan argued. I am to pay what I pay. The economics of the kadavu have not changed.' },
    { id: 'river', gate: f => f.karkidakam, lines: [['Pappan, the thoni pulled high up the steps: “No crossing today. She is angry. See the colour. In fifty-two she came up to the third step of the pally. I was nine. I remember the smell.”', P]], diary: 'Karkidakam. Pappan would not cross; the river was the colour of chaya and moving like it meant it. He remembers the ’52 flood by the smell.' },
    { id: 'breathe', lines: [['Pappan, pointing with the pole: “After rain, there. Where the paddy drains in. The fish come up to breathe. Your Achan knew. He never told anyone else. Now you know. Now you do not tell anyone.”', P]], diary: 'Pappan showed me where the fish come up to breathe after rain, below the paddy drain. Achan knew. I am sworn to not tell, and have told only this diary.' },
    { id: 'leak', lines: [['Pappan, bailing with a coconut shell: “She leaks. Forty years, she leaks. Coir and tar from Kunjappan and a Sunday. You hold, I hammer.”', P], ['A plank the colour of a new tooth in a mouth of old ones. He pats it like a cow.']], diary: 'Spent a Sunday patching Pappan’s thoni with coir and tar. The new plank is the colour of a new tooth. He patted it like a cow.', flag: 'plank' },
    { id: 'vavu', gate: f => f.vavu, lines: [['Pappan, before dawn, ferrying the bali crowd across and back and across, taking nothing: “Today the river is a temple. You do not charge at a temple.”', P]], diary: 'Karkidaka vavu. Pappan ferried the whole village for the bali and took nothing. “Today the river is a temple.”' },
    { id: 'chundan', gate: f => f.onam && clock.day === 23, lines: [['Pappan, watching the chundan vallam go past with a face you have not seen on him: “Nineteen fifty-two. Seat forty. We lost by a boat length. I can still feel the oar.”', P]], diary: 'Pappan rowed seat forty in a chundan in 1952 and lost by a boat length. He watched this year’s race with the oar still in his hands.' },
    { id: 'pole', lines: [['Pappan, holding out the pole: “Take her across. Push, don’t paddle. Feel the bottom. If you fall in, I will tell everyone, so do not.”', P]], diary: 'Pappan let me pole the thoni across. Push, do not paddle. I did not fall in. He will tell everyone that I nearly did.', flag: 'pole' }
  ] },
  kids: { name: 'the children', beats: [
    { id: 'ball', lines: [['The children, at the gate: “Chettaa, our ball is on your roof.” It is always on your roof.', C], ['You throw it down. They are gone before it lands, shouting about a kite.']], diary: 'The children from the next house, who treat our roof as their ball’s second home. Their grandmother did the same, apparently.' },
    { id: 'rhyme', lines: [['The children, in a row, deadly serious: “We will teach you the rhyme. For the kuttikali. Say it. No, say it properly.”', C], ['You say it properly on the fourth try. The smallest one declares you passed, barely.']], diary: 'Learned the kuttikali rhyme from the neighbour’s children, who graded me. Passed on the fourth try, barely.' },
    { id: 'mango', gate: f => f.mango, lines: [['The children, with a mango each and a story: “From Ammini chechi’s tree. She gave them to us.” She did not. “Take one. Then you are also in it.”', C]], diary: 'Accepted a stolen mango from the children so I would be “in it”. Ammini chechi knew before I had finished eating it. The mango was excellent.' },
    { id: 'window', lines: [['A crack of glass from the chayakkada and five children arriving at your gate at once, breathing hard: “Chettaa. Say you did it. He will not shout at you.”', C], ['You tell Velayudhan you did it. He looks at you, at the children behind the wall, at the ball. “Fourteen rupees,” he says, to you, loudly. He writes nothing down.']], diary: 'Took the blame for the chayakkada window. Velayudhan charged me fourteen rupees loudly and wrote nothing down. The children owe me a lifetime of silence and will not pay.' },
    { id: 'anniversary', gate: () => fest().schoolDay && clock.month === 5, lines: [['The school anniversary. The children in paper crowns, the master with a whistle, a play about Mahabali in which Mahabali forgets his lines and is rescued by the smallest one, who knows everyone’s lines.', C]], diary: 'The school anniversary at the pallikkoodam. Mahabali forgot his lines and the smallest child saved the play. The master pretended not to be proud.' },
    { id: 'kite', gate: f => clock.month === 8 || clock.month === 0, lines: [['The children, with a kite made from a Mathrubhumi and broom sticks: “Fly it. You know the wind.” It flies, for a while, and then it is on your roof, where everything of theirs ends up.', C]], diary: 'Flew the children’s newspaper kite until it landed on our roof, where everything of theirs ends up. It is still there. I am leaving it.', flag: 'kiteroof' },
    { id: 'onam', gate: f => f.thiruvonam, lines: [['The children, early, with their skirts and shirts full of flowers: “For your pookalam. Ours is finished. Yours is crooked on the left.”', C]], diary: 'The children brought their leftover flowers for our pookalam on Thiruvonam morning and told me it was crooked on the left. Everybody knows about the left.', flag: 'flowers' }
  ] }
};
function rel(id) { if (!state.rel) state.rel = {}; if (!state.rel[id]) state.rel[id] = { done: {}, lastDay: -99 }; return state.rel[id]; }
export function has(id, flag) { const r = state.rel && state.rel[id]; return !!(r && r.done[flag]); }
// the next beat that is ready: not yet done, its gate (if any) open, and a few days since the last one
export function beatDue(id) {
  const r = rel(id), f = fest(), gap = clock.mode === 'story' ? 1 : 3;
  if (state.days - r.lastDay < gap) return null;
  return ARCS[id].beats.find(b => !r.done[b.id] && (!b.gate || b.gate(f))) || null;
}
export function anyDue(id) { return !!beatDue(id); }
export function playBeat(id) {
  const b = beatDue(id); if (!b) return false; const r = rel(id);
  r.done[b.id] = true; r.lastDay = state.days; audio.sfx('tap'); haptics.soft();
  talk(b.lines, 5); remember('beat_' + id + '_' + b.id, b.diary); if (b.after) b.after(); save(); return true;
}
export function arcProgress(id) { const r = rel(id); return ARCS[id].beats.filter(b => r.done[b.id]).length; }
