// Twelve one-off moments across the year, one a month, each in one place for a few hours. A figure appears, a line is said once, the diary keeps it.
import { state, remember } from './state.js';
import { clock } from './clock.js';
import { say } from '../ui/caption.js';
import { person } from '../art/lib.js';
import { circle, ellipse, rect, line } from '../art/draw.js';
export const SURPRISES = [
  { id: 'snake', m: 1, d: 12, scene: 'kavala', h0: 9, h1: 13, x: 250, y: 650, who: { sex: 'm', top: '#e0b43a', mundu: '#8a2a3a', pose: 'sit', item: 'basket' }, line: 'A snake charmer under the banyan, a basket, a flute that is mostly breath. The cobra is bored. The children are not.', ml: 'പാമ്പാട്ടി', diary: 'A snake charmer at the kavala, the first in years. The cobra was bored and the children were not. Velayudhan says the same man came when he was a boy, which is not possible, and is true.' },
  { id: 'van', m: 2, d: 8, scene: 'pallikkoodam', h0: 10, h1: 14, x: 300, y: 600, who: { sex: 'f', top: '#f6f1e6', mundu: '#f6f1e6', item: 'bag' }, line: 'The vaccination van at the school, a nurse in white, a queue of children in two states: before the needle and after. The master holds the ones who run.', ml: 'വാക്സിൻ വണ്ടി', diary: 'The vaccination van came to the pallikkoodam. The master caught the runners. One boy did not cry and told everyone for a week.' },
  { id: 'pilgrims', m: 3, d: 20, scene: 'poomukham', h0: 7, h1: 11, x: 236, y: 704, who: { sex: 'm', top: '#1a1a1a', mundu: '#1a1a1a', item: 'bag', skin: '#9c6a48' }, line: 'Three Ayyappa pilgrims in black at the gate, asking for water. You draw it from the kinar. One is from Palakkad and knew your Achan’s name.', ml: 'അയ്യപ്പന്മാർ', diary: 'Ayyappa pilgrims in black stopped for water from the kinar. One knew Achan’s name. Amma wrote the same thing in her diary thirty years ago. The world is a small courtyard.' },
  { id: 'band', m: 4, d: 6, scene: 'kavala', h0: 10, h1: 12, x: 280, y: 640, who: { sex: 'm', top: '#c8322a', mundu: '#f3ecd8', cap: '#c8322a' }, line: 'A wedding band comes down the road in red coats and brass, playing a film song too fast, the groom somewhere behind in a car that keeps stalling.', ml: 'ബാൻഡ് സെറ്റ്', diary: 'A wedding band at the kavala in Dhanu, red coats and a trumpet with a dent, playing a Yesudas song at twice the speed. The dog followed them to the river.' },
  { id: 'dark', m: 5, d: 14, scene: 'poomukham', h0: 19, h1: 23, x: 60, y: 704, who: { sex: 'm', top: '#f1e6d0', mundu: '#f3ecd8', pose: 'sit' }, line: 'The transformer at the kavala has gone with a bang and the whole village is dark. Everyone is outside. You have never seen so many stars or heard so many neighbours.', ml: 'കറന്റ് പോയി', diary: 'The transformer went on Makaram 14 and the village sat outside in the dark with the stars and each other. The electricity came back at eleven and everybody was a little sorry.' },
  { id: 'tent', m: 6, d: 10, scene: 'angadi', h0: 17, h1: 22, x: 60, y: 640, who: { sex: 'm', top: '#2a3a8a', mundu: '#f3ecd8', item: 'bag' }, line: 'A touring talkies in a tent behind the angadi: a projector on a bullock cart, a bedsheet screen, benches, and a film that breaks twice and is cheered both times.', ml: 'ടൂറിംഗ് ടാക്കീസ്', diary: 'A tent talkies behind the angadi for the utsavam week. The film broke twice. The second time the whole tent sang the song they knew was coming until it was fixed.' },
  { id: 'well', m: 7, d: 15, scene: 'poomukham', h0: 8, h1: 18, x: 330, y: 704, who: { sex: 'm', top: '#8a7a4a', mundu: '#8a7a4a', item: 'pot' }, line: 'Meenam. The kinar is low; the bucket comes up half full and brown. The well-cleaner has come with his rope and his nephew and no fear at all.', ml: 'കിണർ വറ്റി', diary: 'The well went low in Meenam and the well-cleaner came down it on a rope while his nephew smoked above. He came up with two buckets, a kindi from 1940 and a frog.' },
  { id: 'bioscope', m: 8, d: 20, scene: 'pallikkoodam', h0: 11, h1: 15, x: 80, y: 620, who: { sex: 'm', top: '#e0b43a', mundu: '#f3ecd8', item: 'basket' }, line: 'The bioscope man at the school gate with his box on a bicycle: Delhi, Agra, Bombay, one paisa a look, the children in a queue that keeps rejoining itself.', ml: 'ബയോസ്കോപ്പുകാരൻ', diary: 'The bioscope man at the pallikkoodam gate, the same box as the one in our attic or its brother. The children paid a paisa to see Delhi and asked if it was far.' },
  { id: 'umbrella', m: 9, d: 10, scene: 'kavala', h0: 9, h1: 14, x: 240, y: 660, who: { sex: 'm', top: '#f1e6d0', mundu: '#f3ecd8', pose: 'sit', item: 'umbrella' }, line: 'The umbrella-repair man is at the kavala before the rains, as every year, with a sack of ribs and a mouth full of nails. Half the village’s umbrellas are in a heap at his feet.', ml: 'കുടനന്നാക്കൽ', diary: 'The umbrella man at the kavala before Edavam, nails in his mouth, our old black umbrella in his heap. He remembered it. He remembered Achan buying it.' },
  { id: 'flood', m: 10, d: 20, scene: 'kadavu', h0: 7, h1: 18, x: 40, y: 600, who: { sex: 'm', bare: true, mundu: '#d9d2c0', skin: '#8a5a3a' }, line: 'The river is up over the third step and the colour of chaya. Pappan has pulled the thoni high and sits beside it like a man beside a sick cow.', ml: 'വെള്ളം പൊങ്ങി', diary: 'The river over the third step in Mithunam. Pappan sat beside his beached thoni all day. Nobody crossed. The pally bell came over the water louder than usual.' },
  { id: 'boats', m: 11, d: 20, scene: 'nadumuttam', h0: 10, h1: 17, x: 60, y: 560, who: { sex: 'boy', top: '#e0b43a', mundu: '#6a7fa0', pose: 'sit' }, line: 'The children have come in from the rain and are racing paper boats down the channel in the nadumuttam floor. The Mathrubhumi has never been so useful.', ml: 'കടലാസുതോണി', diary: 'Paper boat races in the nadumuttam channel on a Karkidakam afternoon, the children soaked and shouting, the newspaper reduced to a navy.' },
  { id: 'astrologer', m: 0, d: 5, scene: 'kavala', h0: 9, h1: 13, x: 260, y: 650, who: { sex: 'm', top: '#8a2a3a', mundu: '#f3ecd8', pose: 'sit', item: 'basket' }, line: 'The parrot astrologer under the banyan. For ten paise the bird picks a card. Yours says: a journey, a letter, a long life. The bird looks unconvinced.', ml: 'കിളിജോത്സ്യൻ', diary: 'The parrot astrologer at the kavala in Chingam. The bird picked a card that promised a journey, a letter and a long life. Two out of three have come true already this year.' }
];
export function activeSurprise(sceneName) {
  const h = clock.hour; return SURPRISES.find(s => s.scene === sceneName && s.m === clock.month && s.d === clock.day && h >= s.h0 && h < s.h1) || null;
}
// called by the scene each frame after its own drawing
export function drawSurprise(scene, c, t) {
  const s = activeSurprise(scene.name); if (!s) return;
  person(c, s.x, s.y, .82, s.who, t);
  if (s.id === 'snake') { ellipse(c, s.x + 22, s.y - 2, 10, 4, '#a67c4a'); line(c, s.x + 22, s.y - 6, s.x + 24 + Math.sin(t * 3) * 2, s.y - 24, '#2a2a2a', 3); circle(c, s.x + 24 + Math.sin(t * 3) * 2, s.y - 26, 3, '#2a2a2a'); }
  if (s.id === 'dark') { c.fillStyle = 'rgba(0,0,0,.18)'; c.fillRect(0, 0, 430, 800); for (let i = 0; i < 40; i++) { const x = (i * 97) % 430, y = (i * 53) % 300; c.globalAlpha = .5 + .5 * Math.abs(Math.sin(t + i)); circle(c, x, y, .9, '#fff7e6'); } c.globalAlpha = 1; person(c, 120, 704, .82, { sex: 'f', top: '#8a2a3a', mundu: '#efe6cf', pose: 'sit' }, t); }
  if (s.id === 'boats') { for (let i = 0; i < 3; i++) { const x = 180 + ((t * 20 + i * 40) % 120), y = 500 + i * 3; c.fillStyle = '#f1e4c8'; c.beginPath(); c.moveTo(x - 6, y); c.lineTo(x + 6, y); c.lineTo(x, y - 6); c.closePath(); c.fill(); } person(c, 300, 560, .82, { sex: 'boy', top: '#c8322a', mundu: '#f3ecd8', pose: 'sit', flip: true }, t); }
  if (s.id === 'astrologer' || s.id === 'snake') { /* the basket is the prop */ }
  if (s.id === 'astrologer') { circle(c, s.x + 20, s.y - 36, 3, '#4fa84a'); line(c, s.x + 20, s.y - 33, s.x + 20, s.y - 26, '#4fa84a', 2); }
  if (s.id === 'band') { for (let i = 1; i < 4; i++) person(c, s.x + i * 22, s.y + (i % 2) * 4, .82, { sex: 'm', top: '#c8322a', mundu: '#f3ecd8', cap: '#c8322a', flip: true }, t + i); rect(c, s.x + 8, s.y - 50, 14, 4, '#e0b43a'); }
  if (s.id === 'pilgrims') { person(c, s.x - 26, s.y + 2, .82, { sex: 'm', top: '#1a1a1a', mundu: '#1a1a1a', skin: '#8a5a3a' }, t + 1); person(c, s.x + 26, s.y + 4, .82, { sex: 'm', top: '#1a1a1a', mundu: '#1a1a1a' }, t + 2); }
}
// say the line once when the player is there
export function tickSurprise(sceneName) {
  const s = activeSurprise(sceneName); if (!s) return;
  const key = 'sur_' + s.id + '_' + clock.dayKey(); if (state.today[key]) return; state.today[key] = true;
  setTimeout(() => say(s.line, s.ml, 7), 900); remember('surprise_' + s.id, s.diary);
}
