// Language: 'en' shows English with Malayalam beneath (the default); 'ml' shows Malayalam only wherever a translation exists.
import { state } from '../game/state.js';
import { ML } from './ml.js';
import { GLOSSARY } from '../game/glossary.js';
export const FONT_ML = '"Malayalam Sangam MN","Noto Sans Malayalam","Noto Serif Malayalam",system-ui,sans-serif';
export function lang() { return state.lang === 'ml' ? 'ml' : 'en'; }
// Three ways to read the village: 'en' (Kerala words in Latin letters, an English gloss beneath: Kada · shop), 'enml' (the same with the Malayalam word beneath: Kada · കട), 'ml' (everything in Malayalam)
export function mode() { return state.lang === 'ml' ? 'ml' : state.lang === 'enml' ? 'enml' : 'en'; }
const GLOSS = { 'പൂമുഖം': 'front verandah', 'നടുമുറ്റം': 'inner courtyard', 'അടുക്കള': 'kitchen', 'അറ': 'inner room', 'തൊടി': 'garden', 'കുളം': 'pond', 'തട്ടിൻപുറം': 'attic', 'അമ്പലം': 'temple', 'കാവ്': 'sacred grove', 'ചായക്കട': 'tea shop', 'പലചരക്കുകട': 'provision shop', 'കട': 'shop', 'വായനശാല': 'reading room', 'അങ്ങാടി': 'market street', 'പള്ളിക്കൂടം': 'school', 'ടാക്കീസ്': 'cinema', 'കവല': 'junction', 'വയൽ': 'paddy field', 'കടവ്': 'river landing', 'പള്ളി': 'church', 'സ്റ്റേഷൻ': 'railway station', 'റെയിൽവേ സ്റ്റേഷൻ': 'railway station', 'കടപ്പുറം': 'beach', 'മസ്ജിദ്': 'mosque', 'ബാങ്ക്': 'the call to prayer', 'ഹൗള്': 'the washing tank', 'മദ്രസ': 'the madrasa', 'ഇഫ്താർ': 'iftar', 'പെരുന്നാൾ': 'the feast', 'ഹംസക്ക': 'Hamsakka', 'വെളുപ്പ്': 'dawn', 'രാവിലെ': 'morning', 'ഉച്ച': 'noon', 'സന്ധ്യ': 'dusk', 'രാത്രി': 'night', 'വീട്': 'home', 'ചിങ്ങം': 'the month of Onam', 'ഓണം': 'Onam', 'വിഷു': 'Vishu', 'തിരുവോണം': 'Thiruvonam', 'പൂക്കളം': 'flower carpet', 'നിലവിളക്ക് തെളിഞ്ഞു': 'the lamp is lit', 'കിണർ': 'the well', 'തുളസിത്തറ': 'the basil pedestal', 'ചാരുപടി · മാതൃഭൂമി': 'the bench · the newspaper', 'അടുപ്പ്': 'the hearth', 'അടുപ്പ് കെട്ടു': 'the hearth is cold', 'വിറക്': 'firewood', 'ചമ്മന്തി': 'coconut chutney', 'ഉരൽ': 'the mortar', 'പാൽ': 'milk', 'പാൽക്കാരൻ': 'the milkman', 'മീൻകാരി': 'the fish seller', 'പോസ്റ്റുമാൻ': 'the postman', 'അമ്മിണി ചേച്ചി': 'Ammini chechi', 'കുട്ടികൾ': 'the children', 'മാവേലി': 'Maveli', 'വൈദ്യൻ': 'the physician', 'വേലായുധൻ': 'Velayudhan', 'കുഞ്ഞപ്പൻ': 'Kunjappan', 'പാപ്പൻ': 'Pappan', 'കടത്ത്': 'the ferry', 'ബെഞ്ച്': 'the bench', 'ആനവണ്ടി': 'the bus', 'കണ്ടക്ടർ': 'the conductor', 'പള്ളിമണി': 'the church bell', 'ദീപസ്തംഭം': 'the lamp pillar', 'ഹാർമോണിയം': 'the harmonium', 'കരമടി': 'the shore net', 'പട്ടം': 'the kite', 'കാരംസ്': 'carrom', 'മഴ': 'rain', 'അമ്പലമണി': 'the temple bell', 'ആകാശവാണി': 'All India Radio', 'റേഡിയോ': 'the radio', 'ആട്ടുകട്ടിൽ': 'the swing bed', 'ചൂല്': 'the broom', 'രാമായണം': 'the Ramayanam', 'പൂച്ച': 'the cat', 'കത്തയച്ചു': 'letter posted', 'പോയ നേരത്ത്': 'while you were out', 'നല്ല ദിവസം': 'a good day', 'കഥാസമയം': 'story time', 'വീണ്ടും സ്വാഗതം': 'welcome back', 'ഇലകൾ': 'leaves', 'തേങ്ങ': 'coconut', 'വെള്ളം': 'water', 'വിളമ്പുക': 'serve', 'അരയ്ക്കുക': 'grind', 'ഇളക്കുക': 'stir' };
let REV = null;
// the small line under a word: the Malayalam word, its English meaning, or nothing, by language mode
export function sub(ml) { const m = mode(); if (m === 'ml') return ''; if (m === 'enml') return ml || ''; if (!ml) return ''; if (GLOSS[ml]) return GLOSS[ml]; if (!REV) { REV = {}; try { for (const [en, mlw, meaning] of GLOSSARY) REV[mlw] = meaning; } catch (e) { } } return REV[ml] || ''; }
// translate a whole string; unknown strings come back unchanged so nothing ever goes blank
export function t(s) { if (state.lang !== 'ml' || !s) return s; const m = ML[s]; if (m) return m; return s; }
// pick between an English and a Malayalam form written at the call site
export function pick(en, ml) { return state.lang === 'ml' && ml ? ml : en; }
// number in Malayalam digits? Keep Arabic numerals: Kerala has used them on calendars and clocks since the 1950s.
export const ui = { get scale() { return state.textScale || 1; }, get motion() { return !state.reduceMotion; }, get contrast() { return !!state.highContrast; } };
export function isML(s) { return /[ഀ-ൿ]/.test(s || ''); }
